"""Amazon table

Revision ID: 4588333325a5
Revises: 
Create Date: 2021-01-23 13:32:05.385703

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4588333325a5'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('amazon',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('index', sa.Integer(), nullable=True),
    sa.Column('category', sa.String(), nullable=True),
    sa.Column('product', sa.String(), nullable=True),
    sa.Column('rating', sa.String(), nullable=True),
    sa.Column('reviews', sa.Integer(), nullable=True),
    sa.Column('price', sa.Float(), nullable=True),
    sa.Column('image', sa.String(), nullable=True),
    sa.Column('asin', sa.String(), nullable=True),
    sa.Column('link', sa.String(), nullable=True),
    sa.Column('rating_int', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('amazon')
    # ### end Alembic commands ###
